### ISSUE TITLE
Issues trying out AppFlowy-Cloud on Kubernetes

### ISSUE THREAD

**Issue by benibaeumle** [khorshuheng/appflowy-self-host-resources#1]
Hello,
thanks so much for the awesome work so far. :)
I am just trying out to self-host AppFlowy. I managed to get Appflowy-Cloud running on my own Kubernetes cluster.

All five containers are up and running and can communicate with each other (at least it seems to). I am also able to log in via the admin interface, and I can add new users.

Further, I can use the Ubuntu Snap App Appflowy (version 0.7.9) to log into Appflowy.
Creating documents also works; documents are uploaded to the S3 bucket.

I tried more stuff, and I am experiencing some issues:
  * I tried to invite others to join a workspace. The invitation links are sent but result in an HTTP 404 error when clicked. 
  * Inside the Snap app, share/publish links using the domain appflowy.com and not my custom domain. Even though I configured `AppFlowy Cloud Self-Hosted` in `Cloud Settings`.

Do you have any idea if these are configuration issues or bugs?

I will also create an issue in the web app repo since I am also trying to deploy that and am experiencing problems with the domain it uses.

Here are infos about my configuration:

* I create the ingresses manually since I need to add annotations, but the ingresses are identical to those in the helm chart + my annotations
* I already have a Postgres instance running
* I did the setup job manually since granting admin access to any app is too scary for me
* I use an AWS bucket as object storage
* I created a separate secret for all the sensitive info. That's why I left the values in `values.yaml` blank

1. `values.yaml`:

    ```yaml
    global:
      scheme: http
      externalHost: "appflowy.mydomain.com"
      externalPort: 80
      ingress:
        nginx:
          enabled: false
          className: nginx
        traefik:
          enabled: false
      gotrue:
        adminEmail: "appflowy@mydomain.com"
      database:
        host: postgres.mydomain.com
        name: appflowydb
        port: 5432
        username: appflowy
        adminUsername: appflowy
      s3:
        createBucket: "false"
        useMinio: "false"
        bucket: "mybucket"
        minioUrl: "https://mybucket.s3.eu-central-1.amazonaws.com"
        accessKey: "myaccesskey"
        region: "eu-central-1"
      smtp:
        host: "mail.mydomain.com"
        port: 587
        user: "appflowy@mydomain.com"
        email: "appflowy@mydomain.com"
        tlsKind: "required"
      ai:
        enabled: false
      appflowyWeb:
        enabled: true
        url: "https://appflowy.mydomain.com"
      secret:
        name: appflowy
        create: false
        postgres:
          adminPassword:
            key: postgresAdminPassword
            value: ""
          gotrue:
            postgresPassword:
              key: gotruePostgresPassword
              value: ""
            databaseUrl:
              key: gotrueDatabaseUrl
              value: ""
          appflowy:
            postgresPassword:
              key: postgresPassword
              value: ""
            databaseUrl:
              key: appflowyDatabaseUrl
              value: ""
        gotrue:
          adminPasword:
            key: gotrueAdminPassword
            value: ""
        jwt:
          secret:
            key: jwtSecret
            value: ""
        smtp:
          password:
            key: smtpPassword
            value: ""
        s3:
          secret:
            key: s3Secret
            value: ""
    
    appflowy-admin:
      enabled: true
      fullnameOverride: appflowy-admin
    appflowy-gotrue:
      enabled: true
      fullnameOverride: appflowy-gotrue
      mailer:
        enabled: true
        autoConfirm: false
        adminEmail: "appflowy@mydomain.com"
    appflowy-cloud:
      enabled: true
      fullnameOverride: appflowy-cloud
      accessControl:
        enabled: true
      ingress:
        enabled: false
    
    redis:
      enabled: true
      auth:
        enabled: false
        master:
          persistence:
            enabled: false
    
    # use existing postgres and minio servers
    postgresql:
      enabled: false
    minio:
      enabled: false
    
    setupJob:
      enabled: false
  ```

**Comment by khorshuheng** [comment]
Thanks for trying out the chart. I will update the chart to include AppFlowy Web so that it will be available out of the box, under the same domain as AppFlowy Cloud.

**Comment by khorshuheng** [comment]
As for the other issues raised:

**On shared/published link:**
- The AppFlowy Web domain is configured on the client side, and is available in App version 0.8.1 and above.
This was done before we update the installation to install both AppFlowy Web and AppFlowy Cloud under a single domain. In the future, the AppFlowy Web domain should be the same as AppFlowy Cloud by default.

**For the 404 on invitation link**
- Could you tell me how the invitation link looks like? After masking the sensitive details.

**Annotations on Ingress**
- I can probably add support for adding custom annotation on the ingress, will look into this.

**Others**
- Yes, we should use separate secrets. Secrets should not be in the values file, unless it is for quick testing purpose (eg. in minikube).
- Yeah, ideally we shouldn't have a migration job that requires credential for postgres superuser, but i have not been able to found a way to get rid of this requirement, unfortunately.

**Comment by benibaeumle** [comment]
Thanks again for the quick reply. I will be happy to try out the chart updates and give feedback.

**For the 404 on invitation link**:
  * the links looks like this: `https://appflowy.mydomain.com/accept-invitation?invited_id=cb041719-xxxx-xxxx-xxxx-fdfabb7a18be`

**Annotations on Ingress**
  * Sounds nice.

**Others**
  * for the migration script. I guess having docs telling how to do it manually should be ok.

**Comment by khorshuheng** [comment]
The link will only look like that if AppFlowy Web URL has been set.
```
  appflowyWeb:
    enabled: true
    url: "https://appflowy.mydomain.com"
```
And for the current helm chart, appflowy web is assumed to be hosted on a separate domain. And hence the url should not be the same as appflowy cloud domain.

For the new version of the chart, where appflowy web is bundled together with the rest of the service, this should no longer be an issue, as admin frontend will be accessible via /console instead.

**Comment by benibaeumle** [comment]
Thanks for the suggestion. I configured it to point to the correct domain, which is `https://web.appflowy.mydomain.com`. 
But then I run into the AppFlowy-Web issue that the AppFlowy-Web sends requests to the official AppFlowy domain instead of the self-hosted one.

So, I think I must wait for the Helm chart update. Thanks a lot for the feedback. :)

**Comment by khorshuheng** [comment]
I have updated the helm chart to include support for additional annotations from the user, and also appflowy web. Also added a quick start guide with Minikube:
https://github.com/khorshuheng/appflowy-self-host-resources/blob/main/charts/README.md

**Comment by khorshuheng** [comment]
I haven't gone through all the logs and your configuration in details, but based on the redirect URL pattern, it seems that you might have missed the step to make nginx allow underscore in headers:

https://github.com/khorshuheng/appflowy-self-host-resources/tree/main/charts#quick-start-with-minikube

I will check your configuration and logs again later.

**Comment by benibaeumle** [comment]
Thx, that was the issue :/

For some reason, I set it to `enabled`:

```yaml
data:
  enable-underscores-in-headers: "enabled"
```

Setting it `true` fixed it:

```yaml
data:
  enable-underscores-in-headers: "true"
```

Thx so much. I will try out the setup the next days. :)

**Comment by khorshuheng** [comment]
For the record - it is certainly not a good thing to have underscore in header, consider that many reverse proxy either drop it or canonicalize the headers with underscore. Although, to solve this I will have to use a customize version of gotrue. (The one AppFlowy use is already customized, but more changes are required).

I am considering if I should include my own gotrue service image here as well, instead of the official one in the AppFlowy repo, since there is no backward compatibility concern if I introduce the change here. It might help with other things as well, like simplifying the migration.

**Comment by benibaeumle** [comment]
I am happy to disable it again. On the other hand, I don't see a security concern with enabling it. Or is there anything I am missing?

If you need someone to try out a customized image that lets you disable underscores in headers again, I am happy to help.

**Comment by khorshuheng** [comment]
There's no security concern, just that, it might cause issues for certain setup. For example, if you have Caddy reverse proxy in front of the ingress controller, this won't work because there is no option to allow underscore in header for Caddy. Caddy will automatically convert the underscore to dash.

Also, it's far to easy to forget to enable that change on nginx controller.

Lastly, it's also rather awkward to require supabase_auth_admin user to be created on postgres (not even possible to rename), especially when the AppFlowy cloud expect the AppFlowy postgres users to be able to have full access to whatever postgres resource that supabase_auth_admin can.

**Comment by benibaeumle** [comment]
Ok, I see the problems, especially with the Caddy example.

I don't understand why the user management is implemented like that. I thought the supabase_auth_admin must sure be a requirement to enable both hosting solutions. But, in general, I don't see why it's needed.

**Comment by khorshuheng** [comment]
There are multiple reasons:
- Currently, in AppFlowy Cloud schema migrations, we have this: https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/6a816341bffb82ac3a1f2efc711fb3cd7bf0a4a0/migrations/20231130140000_user_delete_trigger.sql#L4

This was meant to automatically cleanup the record on Appflowy cloud tables if a user has been removed via gotrue API directly. However, in practice, this does not happen in regular workflow. The side effect of having this migration file, is that it became mandatory to have a postgres user named "supabase_auth_admin". And there's no way to parameterize this because the migration scripts are embedded as part of AppFlowy cloud binary, during compilation.

- We have some workflow on Appflowy cloud/postgres migration that access tables managed by gotrue service directly, rather than calling gotrue API. Hence, it became necessary to grant the table access to the AppFlowy postgres users, which is really not ideal.

- Typically, Supabase Auth/Gotrue assumes that the tables are under a postgres schema named "auth" instead of the "public" schema. This seems to be configurable on the Supabase Auth end, but we haven't really tested this. The side effect, is that there needs to be a migration step to create this new schema and grant access to a user, which complicates migration.

**Comment by benibaeumle** [comment]
Not so easy to work around that :/

The following no longer relates to this issue, but please forgive me for using the issue to ask.

What do you think about an update on how to install this helm chart?

I have an internal wiki entry that looks something like the following. Something along those lines would have saved me some time. :)

 And maybe you could add an option to the ingresses for tls, e.g. like this (haven't tested it so far):

```yaml
{{- if .Values.global.ingress.nginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appflowy-admin.fullname" . }}
  {{- with .Values.ingress.nginx.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.nginx.className }}
  {{- if .Values.global.ingress.nginx.tls }}
  tls:
    - hosts:
        - {{ .Values.global.externalHost }}
      secretName: {{ .Values.global.ingress.nginx.tls.secretName }}
  {{-end }}
  rules:
    - host: {{ .Values.global.externalHost }}
      http:
        paths:
          - path: /console
            pathType: Prefix
            backend:
              service:
                name: {{ include "appflowy-admin.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
```

That would enable to use something like Let's Encrypt with the following config:

```yaml
global:
  scheme: https
  externalHost: "appflowy.byteskate.de"
  externalPort: 443
  ingress:
    nginx:
      enabled: true
      className: nginx
      extraAnnotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls:
        secretName: "appflowy-ingress-tls-cert"
        
``` 

And here is my internal wiki entry, maybe something like this at the right place can help someone else to get started :)

# Deploy AppFlowy on K8s

Here you can find a first version of a helm chart for `AppFlowy`: https://github.com/khorshuheng/appflowy-self-host-resources/tree/main/charts/appflowy

The helm chart wants you to add an admin postgres user. To avoid that we can run the setup procedure by hand.

1. Create a database and a user in postgres
2. Install `pgvector` extension for the database.
3. Create the role `supabase_auth_admin`, which will be used by the `gotrue` server. The steps are taken from the setup script, which would require admin privileges:
    ```bash
    # connect to the appflowydb
    \c appflowydb
    CREATE USER supabase_auth_admin BYPASSRLS NOINHERIT CREATEROLE LOGIN NOREPLICATION;
    # an extra schema which will be used by the supabase_auth_admin to handle authentication separated from the rest of the setup
    CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION supabase_auth_admin;
    GRANT USAGE ON SCHEMA auth TO appflowy;
    GRANT CREATE ON DATABASE appflowydb TO supabase_auth_admin;
    GRANT CONNECT ON DATABASE appflowydb TO supabase_auth_admin;
    GRANT supabase_auth_admin TO appflowy;
    # make supabase_auth_admin use schema auth per default
    ALTER USER supabase_auth_admin SET search_path = 'auth';
    # password later used in secrets
    # for convenience we use the same password for the user appflowy and the user supabase_auth_admin
    ALTER USER supabase_auth_admin WITH PASSWORD 'password';
    # create pgvector extension for AI stuff
    CREATE EXTENSION IF NOT EXISTS vector;
    ```
3. Make sure the two secrets for the database urls have the correct format.
   * `appflowyDatabaseUrl`: `postgresql://appflowy:$password@postgres.yourdomain.com:5432/appflowydb`
   * `gotrueDatabaseUrl`: `postgresql://supabase_auth_admin:$password@postgres.yourdomain.com:5432/appflowydb`
   
    ==> Note the difference in username. appflowy will use schema public and gotrue schema `auth` as initialized above

4. Create a secret file containing all sensitive information:
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: appflowy
      namespace: appflowy
    type: Opaque
    stringData:
      postgresAdminPassword: "$password"
      appflowyDatabaseUrl: "postgresql://appflowy:$password@postgres.yourdomain.com:5432/appflowydb"
      postgresPassword: "$gotrue_postgres_password"
      gotrueDatabaseUrl: "postgresql://supabase_auth_admin:$password@postgres.yourdomain.com:5432/appflowydb"
      gotruePostgresPassword: "$gotrue_postgres_password"
      gotrueAdminPassword: "$gotrue_web_login_password"
      jwtSecret: "$jwt_secret"
      smtpPassword: "$mail_password"
      s3Secret: "$s3_api_key_secret"
    ```

**Comment by khorshuheng** [comment]
Added support for Nginx TLS in ingress, though i haven't tested it end to end, as I am not using Nginx for my own deployment at the moment.

**Comment by bernardgut** [comment]
@benibaeumle did you ever manage to make it work ?

**Comment by benibaeumle** [comment]
@bernardgut yes, I managed to set it up back then. I still have crude docs on how I did it. I can provide it to you herewith. But, it may have changed of course in the meanwhile (my last commit was 5 months ago).

# Deploy AppFlowy on K8s

## Prerequirements

### PostgreSQL Setup

1. Create a database and a user
2. Install `pgvector`
3. Create the role `supabase_auth_admin`, which will be used by the `gotrue` server. The steps are taken from the setup script, which would require admin privileges:

   ```shell
    # connect to the appflowydb
    \c appflowydb
    CREATE USER supabase_auth_admin BYPASSRLS NOINHERIT CREATEROLE LOGIN NOREPLICATION;
    # an extra schema which will be used by the supabase_auth_admin to handle authentication separated from the rest of the setup
    CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION supabase_auth_admin;
    GRANT USAGE ON SCHEMA auth TO appflowy;
    GRANT CREATE ON DATABASE appflowydb TO supabase_auth_admin;
    GRANT CONNECT ON DATABASE appflowydb TO supabase_auth_admin;
    GRANT supabase_auth_admin TO appflowy;
    # make supabase_auth_admin use schema auth per default
    ALTER USER supabase_auth_admin SET search_path = 'auth';
    # password later used in secrets
    # for convenience we use the same password for the user appflowy and the user supabase_auth_admin
    ALTER USER supabase_auth_admin WITH PASSWORD 'password';
    # create pgvector extension for AI stuff
    CREATE EXTENSION IF NOT EXISTS vector;
    ```

### Secrets Setup 

1. Create a secret file containing all sensitive information:
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: appflowy
      namespace: appflowy
    type: Opaque
    stringData:
      postgresAdminPassword: "$password"
      appflowyDatabaseUrl: "postgresql://appflowy:$password@postgres.example.com:5432/appflowydb"
      postgresPassword: "$gotrue_postgres_password"
      gotrueDatabaseUrl: "postgresql://supabase_auth_admin:$password@postgres.example.com:5432/appflowydb"
      gotruePostgresPassword: "$gotrue_postgres_password"
      gotrueAdminPassword: "$gotrue_web_login_password"
      jwtSecret: "$jwt_secret"
      smtpPassword: "$mail_password"
      s3Secret: "$s3_api_key_secret"
    ```

## Deploy Files

1. `helmfile.yaml` (**version must probably be adapted**):

    ```yaml
    releases:
      - name: appflowy
        namespace: appflowy
        chart: ./appflowy-0.1.21.tgz
        version: 0.1.21
        values:
          - values.yaml
    ```

2. `values.yaml`:

    ```
    global:
      scheme: https
      externalHost: "appflowy.example.com"
      externalPort: 443
      ingress:
        nginx:
          enabled: false
          className: nginx
        traefik:
          enabled: false
      gotrue:
        adminEmail: "user@example.com"
      database:
        host: postgres.example.com
        name: appflowydb
        port: 5432
        username: appflowy
        adminUsername: appflowy
      s3:
        createBucket: "false"
        useMinio: "false"
        bucket: "bucket-k8s-appflowy"
        minioUrl: "https://bucket-k8s-appflowy.s3.eu-central-1.amazonaws.com"
        accessKey: "$key"
        region: "eu-central-1"
      smtp:
        host: "mail.your-server.de"
        port: 587
        user: "appflowy@example.com"
        email: "appflowy@example.com"
        tlsKind: "required"
      ai:
        enabled: false
      secret:
        name: appflowy
        create: false
        postgres:
          adminPassword:
            key: postgresAdminPassword
            value: ""
          gotrue:
            postgresPassword:
              key: gotruePostgresPassword
              value: ""
            databaseUrl:
              key: gotrueDatabaseUrl
              value: ""
          appflowy:
            postgresPassword:
              key: postgresPassword
              value: ""
            databaseUrl:
              key: appflowyDatabaseUrl
              value: ""
        gotrue:
          adminPasword:
            key: gotrueAdminPassword
            value: ""
        jwt:
          secret:
            key: jwtSecret
            value: ""
        smtp:
          password:
            key: smtpPassword
            value: ""
        s3:
          secret:
            key: s3Secret
            value: ""
    
    appflowy-admin:
      enabled: true
      fullnameOverride: appflowy-admin
    appflowy-gotrue:
      enabled: true
      fullnameOverride: appflowy-gotrue
      mailer:
        enabled: true
        autoConfirm: false
        adminEmail: "appflowy@example.com"
    appflowy-cloud:
      enabled: true
      fullnameOverride: appflowy-cloud
      accessControl:
        enabled: true
      ingress:
        enabled: false
    appflowy-web:
      enabled: true
      fullnameOverride: appflowy-web
      ingress:
        enabled: false
    
    redis:
      enabled: true
      auth:
        enabled: false
        master:
          persistence:
            enabled: false
    
    # use existing postgres and minio servers
    postgresql:
      enabled: false
    minio:
      enabled: false
    
    setupJob:
      enabled: false
    ```

3. I used a custom ingress, because it was not supported back then, `ingress.yaml`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/32
    nginx.ingress.kubernetes.io/proxy-body-size: 20000m
  name: appflowy-admin
  namespace: appflowy
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - appflowy.example.com
    secretName: appflowy-web-ingress-cert
  rules:
  - host: appflowy.example.com
    http:
      paths:
      - path: /console
        pathType: Prefix
        backend:
          service:
            name: appflowy-admin
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/32
    nginx.ingress.kubernetes.io/proxy-body-size: 20000m
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://appflowy.example.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization, Accept, Client-Version"
    nginx.ingress.kubernetes.io/cors-max-age: "3600"
  name: appflowy-cloud-api
  namespace: appflowy
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - appflowy.example.com
    secretName: appflowy-web-ingress-cert
  rules:
  - host: appflowy.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: appflowy-cloud
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/32
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
  name: appflowy-cloud-ws
  namespace: appflowy
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - appflowy.example.com
    secretName: appflowy-web-ingress-cert
  rules:
  - host: appflowy.example.com
    http:
      paths:
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: appflowy-cloud
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/32
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: appflowy-gotrue
  namespace: appflowy
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - appflowy.example.com
    secretName: appflowy-web-ingress-cert
  rules:
  - host: appflowy.example.com
    http:
      paths:
      - path: /gotrue(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: appflowy-gotrue
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/32
  name: appflowy-web
  namespace: appflowy
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - appflowy.example.com
    secretName: appflowy-web-ingress-cert
  rules:
  - host: appflowy.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: appflowy-web
            port:
              number: 80
```



## Deploy Script

The deploy script I used in my GitLab CI/CD pipeline:

```yaml
upgrade_appflowy:
    stage: apply
    tags:
        - gitlab-runner-broker
    script:
        - kubectl apply -f $APPFLOWY_SECRET
        - git clone https://github.com/khorshuheng/appflowy-self-host-resources.git
        - helm dependency update appflowy-self-host-resources/charts/appflowy
        - helm package appflowy-self-host-resources/charts/appflowy
        - helmfile apply
        - kubectl apply -f ingresses.yaml
        - kubectl apply -f networkpolicies.yaml
    when: manual
```
