### ISSUE TITLE
openAI key is missing in secret.yaml

### ISSUE THREAD

**Issue by casabre** [khorshuheng/appflowy-self-host-resources#4]
Hi @khorshuheng,

thanks for creating this Helm chart. I wanted to use the AI feature with the openAI API key provided by the `appflowy` secret
```yaml
global:
  secret:
    # -- Name of the secret which stores all the sensitive information required for AppFlowy
    name: appflowy
    # -- Create or update the Kubernetes secret. If set to false, the secret must be created manually, and the name should be adjusted accordingly. Otherwise, a new
    # -- secret will be created with the values specified in helm values.
    create: true
    ai:
      openAIAPIKey:
        # -- Secret key name for the OpenAI API key
        key: openAIAPIKey
        # -- Secret value for the OpenAI API key. Leave this empty if you don't wish to use OpenAI.
        value: "any Value"
```
However, the key was never stored in the secret &rarr; https://github.com/khorshuheng/appflowy-self-host-resources/blob/20c360fbcb876263421e0a5fc572d35e1c5a497f/charts/appflowy/templates/secret.yaml#L9

I guess, this is the main reason why the deployment failed.
